inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/*.rb
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  IgnoredPatterns:
    - '# '

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - app/models/user.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 8
