version: '3.9'

services:
  web: &app_base
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  webpacker:
    <<: *app_base
    command: bash -c "rm -rf public/packs && bin/webpack-dev-server"
    ports:
      - 3035:3035

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    security_opt:
      - seccomp:unconfined

volumes:
  bundle-data:
  db-data:
