x-app: &app
  build:
    context: .
    args:
      RUBY_VERSION: '2.7.3'
      PG_MAJOR: '13'
      NODE_MAJOR: '16'
      YARN_VERSION: '1.22.10'
  environment: &environment
    TZ: Asia/Tokyo
    YARN_CACHE_FOLDER: /myapp/node_modules/.yarn-cache
  tmpfs:
    - /myapp/tmp/pids
    - /tmp
  volumes:
    - .:/myapp:cached
    - node_modules:/myapp/node_modules
    - assets:/myapp/public/assets
    - packs:/myapp/public/packs
    - packs-test:/myapp/public/packs-test
    - rails_cache:/myapp/tmp/cache
    - bundle:/usr/local/bundle

version: '3.9'

services:
  app:
    <<: *app
    command: ./bin/rails s -b 0.0.0.0
    depends_on:
      - db
    environment:
      <<: *environment
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      REDIS_URL: redis://redis:6379
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  chrome:
    image: selenium/standalone-chrome:95.0
    ports:
      - 4444:4444

  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C.UTF-8
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    environment:
      <<: *environment
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035

volumes:
  assets:
  bundle:
  db_data:
  node_modules:
  packs:
  packs-test:
  rails_cache:
