version: 2.1

orbs:
  ruby: circleci/ruby@1.3.0
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: 'Update Node.js and npm'
          command: |
            curl -sSL "https://nodejs.org/dist/v14.18.1/node-v14.18.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v14.18.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
      - node/install-packages:
          pkg-manager: yarn
          cache-key: 'yarn.lock'

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.3-node
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ''
      - image: selenium/standalone-chrome:95.0
        name: chrome
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: postgres
      RAILS_ENV: test
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: 'yarn.lock'
      - run:
          name: Install imagemagick
          command: |
            sudo apt-get update
            sudo apt-get install imagemagick
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: tmp/screenshots
      - ruby/rubocop-check
      - store_artifacts:
          path: /tmp/rubocop-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
